# Generated by Django 3.2.5 on 2021-07-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='package',
            field=models.CharField(choices=[('30mbps', '30mbps'), ('55mbps', '55mbps'), ('80mbps', '80mbps'), ('125mbps', '125mbps')], default='25mbps', max_length=255),
        ),
    ]
